# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\x12\x06search\"\x9f\x01\n\x12SearchQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\x12:\n\x08metadata\x18\x03 \x03(\x0b\x32(.search.SearchQueryRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xc7\x02\n\x0cSearchResult\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0bobject_name\x18\x02 \x01(\t\x12\x0e\n\x06\x62ucket\x18\x03 \x01(\t\x12\x12\n\nsize_bytes\x18\x04 \x01(\x03\x12\x14\n\x0c\x63ontent_type\x18\x05 \x01(\t\x12\x11\n\textension\x18\x06 \x01(\t\x12\x15\n\rlast_modified\x18\x07 \x01(\t\x12\x16\n\x0esemantic_score\x18\x08 \x01(\x02\x12\x15\n\rkeyword_score\x18\t \x01(\x02\x12\x16\n\x0e\x63ombined_score\x18\n \x01(\x02\x12\x38\n\nhighlights\x18\x0b \x03(\x0b\x32$.search.SearchResult.HighlightsEntry\x1a\x31\n\x0fHighlightsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x9a\x01\n\x13SearchQueryResponse\x12%\n\x07results\x18\x01 \x03(\x0b\x32\x14.search.SearchResult\x12\x12\n\ntotal_hits\x18\x02 \x01(\x05\x12\x13\n\x0bintent_text\x18\x03 \x01(\t\x12\x1a\n\x12\x65xtracted_keywords\x18\x04 \x03(\t\x12\x17\n\x0f\x61pplied_filters\x18\x05 \x03(\t2W\n\x0cSearchWorker\x12G\n\x0cProcessQuery\x12\x1a.search.SearchQueryRequest\x1a\x1b.search.SearchQueryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHQUERYREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_SEARCHQUERYREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SEARCHRESULT_HIGHLIGHTSENTRY']._loaded_options = None
  _globals['_SEARCHRESULT_HIGHLIGHTSENTRY']._serialized_options = b'8\001'
  _globals['_SEARCHQUERYREQUEST']._serialized_start=25
  _globals['_SEARCHQUERYREQUEST']._serialized_end=184
  _globals['_SEARCHQUERYREQUEST_METADATAENTRY']._serialized_start=137
  _globals['_SEARCHQUERYREQUEST_METADATAENTRY']._serialized_end=184
  _globals['_SEARCHRESULT']._serialized_start=187
  _globals['_SEARCHRESULT']._serialized_end=514
  _globals['_SEARCHRESULT_HIGHLIGHTSENTRY']._serialized_start=465
  _globals['_SEARCHRESULT_HIGHLIGHTSENTRY']._serialized_end=514
  _globals['_SEARCHQUERYRESPONSE']._serialized_start=517
  _globals['_SEARCHQUERYRESPONSE']._serialized_end=671
  _globals['_SEARCHWORKER']._serialized_start=673
  _globals['_SEARCHWORKER']._serialized_end=760
# @@protoc_insertion_point(module_scope)
