// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: proto/search.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// SearchWorkerClient is the client API for SearchWorker service.
type SearchWorkerClient interface {
	ProcessQuery(ctx context.Context, in *SearchQueryRequest, opts ...grpc.CallOption) (*SearchQueryResponse, error)
}

type searchWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchWorkerClient(cc grpc.ClientConnInterface) SearchWorkerClient {
	return &searchWorkerClient{cc}
}

func (c *searchWorkerClient) ProcessQuery(ctx context.Context, in *SearchQueryRequest, opts ...grpc.CallOption) (*SearchQueryResponse, error) {
	out := new(SearchQueryResponse)
	err := c.cc.Invoke(ctx, "/search.SearchWorker/ProcessQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchWorkerServer is the server API for SearchWorker service.
type SearchWorkerServer interface {
	ProcessQuery(context.Context, *SearchQueryRequest) (*SearchQueryResponse, error)
	mustEmbedUnimplementedSearchWorkerServer()
}

// UnimplementedSearchWorkerServer must be embedded to have forward-compatible implementations.
type UnimplementedSearchWorkerServer struct{}

func (UnimplementedSearchWorkerServer) ProcessQuery(context.Context, *SearchQueryRequest) (*SearchQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessQuery not implemented")
}
func (UnimplementedSearchWorkerServer) mustEmbedUnimplementedSearchWorkerServer() {}

// UnsafeSearchWorkerServer may be embedded to opt out of forward compatibility.
type UnsafeSearchWorkerServer interface {
	mustEmbedUnimplementedSearchWorkerServer()
}

func RegisterSearchWorkerServer(s grpc.ServiceRegistrar, srv SearchWorkerServer) {
	s.RegisterService(&SearchWorker_ServiceDesc, srv)
}

func _SearchWorker_ProcessQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchWorkerServer).ProcessQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.SearchWorker/ProcessQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchWorkerServer).ProcessQuery(ctx, req.(*SearchQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var SearchWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search.SearchWorker",
	HandlerType: (*SearchWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessQuery",
			Handler:    _SearchWorker_ProcessQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/search.proto",
}
