// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/search.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query    string            `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit    int32             `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Metadata map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SearchQueryRequest) Reset()         {}
func (x *SearchQueryRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *SearchQueryRequest) ProtoMessage()  {}

func (x *SearchQueryRequest) ProtoReflect() protoreflect.Message {
	return nil // simplified stub
}

func (x *SearchQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchQueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchQueryRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SearchResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ObjectName    string            `protobuf:"bytes,2,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	Bucket        string            `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	SizeBytes     int64             `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ContentType   string            `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Extension     string            `protobuf:"bytes,6,opt,name=extension,proto3" json:"extension,omitempty"`
	LastModified  string            `protobuf:"bytes,7,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	SemanticScore float32           `protobuf:"fixed32,8,opt,name=semantic_score,json=semanticScore,proto3" json:"semantic_score,omitempty"`
	KeywordScore  float32           `protobuf:"fixed32,9,opt,name=keyword_score,json=keywordScore,proto3" json:"keyword_score,omitempty"`
	CombinedScore float32           `protobuf:"fixed32,10,opt,name=combined_score,json=combinedScore,proto3" json:"combined_score,omitempty"`
	Highlights    map[string]string `protobuf:"bytes,11,rep,name=highlights,proto3" json:"highlights,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SearchResult) Reset()         {}
func (x *SearchResult) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *SearchResult) ProtoMessage()  {}
func (x *SearchResult) ProtoReflect() protoreflect.Message { return nil }

func (x *SearchResult) GetId() string            { return x.Id }
func (x *SearchResult) GetObjectName() string     { return x.ObjectName }
func (x *SearchResult) GetBucket() string         { return x.Bucket }
func (x *SearchResult) GetSizeBytes() int64       { return x.SizeBytes }
func (x *SearchResult) GetContentType() string    { return x.ContentType }
func (x *SearchResult) GetExtension() string      { return x.Extension }
func (x *SearchResult) GetLastModified() string   { return x.LastModified }
func (x *SearchResult) GetSemanticScore() float32 { return x.SemanticScore }
func (x *SearchResult) GetKeywordScore() float32  { return x.KeywordScore }
func (x *SearchResult) GetCombinedScore() float32 { return x.CombinedScore }
func (x *SearchResult) GetHighlights() map[string]string { return x.Highlights }

type SearchQueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results           []*SearchResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	TotalHits         int32           `protobuf:"varint,2,opt,name=total_hits,json=totalHits,proto3" json:"total_hits,omitempty"`
	IntentText        string          `protobuf:"bytes,3,opt,name=intent_text,json=intentText,proto3" json:"intent_text,omitempty"`
	ExtractedKeywords []string        `protobuf:"bytes,4,rep,name=extracted_keywords,json=extractedKeywords,proto3" json:"extracted_keywords,omitempty"`
	AppliedFilters    []string        `protobuf:"bytes,5,rep,name=applied_filters,json=appliedFilters,proto3" json:"applied_filters,omitempty"`
}

func (x *SearchQueryResponse) Reset()         {}
func (x *SearchQueryResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *SearchQueryResponse) ProtoMessage()  {}
func (x *SearchQueryResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *SearchQueryResponse) GetResults() []*SearchResult       { return x.Results }
func (x *SearchQueryResponse) GetTotalHits() int32               { return x.TotalHits }
func (x *SearchQueryResponse) GetIntentText() string             { return x.IntentText }
func (x *SearchQueryResponse) GetExtractedKeywords() []string    { return x.ExtractedKeywords }
func (x *SearchQueryResponse) GetAppliedFilters() []string       { return x.AppliedFilters }

var _ sync.Locker  // suppress unused import
var _ reflect.Type // suppress unused import
